### ISSUE TITLE
New Agency Request

### ISSUE THREAD

**Issue by eschuchardt** [bradmont/OpenMPD#41]
@bradmont, Reliant Mission, formerly Great Commission Ministries, has a TntMPD datasyc file that they create, but I've noticed that Reliant is not one of the options on OpenMPD.  What would I need to do in order to get this app to a point where someone from Reliant can use this system?

**Comment by bradmont** [comment]
Hey @eschuchardt, I've been using Troy Wolbrink's organisation list from TntMPD, which is available here:
http://download.tntware.com/tntmpd/TntMPD_Organizations.csv . It doesn't look like Reliant Mission is on there either; does your organisation use Tnt Dataserver (where TntMPD connects to a server to download donor info), or a file download that you then open in TNT? Unfortunately OpenMPD only works with the former. But if that's the way your organisation operates, it's pretty easy to add to OpenMPD if you can give me your query.ini or tntquery.aspx link.

**Comment by eschuchardt** [comment]
Oh OK. That makes sense. It does not use the data server, but rather a
direct file.  In order to get to access the link I need to be logged into
my account, so you wouldn't just be able to pull it directly from their
website.  So I guess I don't understand exactly what you need. Pictured is
the link that we go to to get the file.

**Comment by bradmont** [comment]
Unfortunately working with this type of setup isn't feasible, there is no reliable way to log in to a passworded website to download data. So I don't think I'll be able to help you unless your organisation changes their system. Sorry! :(
